listener 1883
allow_anonymous true
 
connection thingspeak-bridge
address mqtt3.thingspeak.com:1883
remote_username MjsWEjAMFiwbHSIxPQQLCAI
remote_password KT71vP0PtGUltzWt9/62FLrB
remote_clientid MjsWEjAMFiwbHSIxPQQLCAI
try_private false
notifications false
cleansession true
start_type automatic
topic channels/3493100/publish out 0